function [out] = evaluateDNN(in, net)
% function to evaluate DNN for a given input
% in is the test input
% net is the neural network
% out is n x number of outputs matrix of outputs generated by NN

% extract weights and biases from neural network
L = net.numLayers;
W = cell(L,1);
b = cell(L,1);
W{1} = net.IW{1};
b{1} = net.b{1};
for i = 2:L
    W{i} = net.LW{i,i-1};
    b{i} = net.b{i};
end
if (length(in) ~= net.inputs{1}.size)
    error("Input to NN has the wrong shape.")
else
    z = max(W{1} * in + b{1},0);
    for i = 2:L
        z = max(W{i} * z + b{i},0);
    end
    out = z;
end